import Header from "@/components/Header";
import { Box, Container } from "@chakra-ui/react";
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const LayoutUser = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <Box>
            <Header />
            <Box pt={16} as="main">
                {children}
            </Box>
        </Box>
    )
}

export default LayoutUser